### PR TITLE
add: segment to quiz config

### PR DESCRIPTION
**Pull request by akmil**
add: segment to quiz config
split Core in smaller components

### CODE REVIEW

**Comment by wingkwong** [comment]
@akmil thanks for the PR. However, it shows the empty page with the below error after finishing the quiz.

image

**Comment by akmil** [comment]
> @akmil thanks for the PR. However, it shows the empty page with the below error after finishing the quiz.
> 
> image

Oh yes, added commit: move Explanation to separate component

**Comment by wingkwong** [comment]
Some logic is wrong on the result page.

1. I answered correctly but the answer came with incorrect tag. 

image

2. Explanation is not rendered (Left: Your PR v.s. Right: Existing Demo)

3. The correct ans is not highlighted (Left: Your PR v.s. Right: Existing Demo)

image

Both based on the following settings
```js
      <Quiz
        quiz={quiz}
        shuffle={true}
        showInstantFeedback={true}
        continueTillCorrect={true}
        onComplete={setQuizResult}
      />
```

Please try out different settings and compare with [the existing demo](https://wingkwong.github.io/react-quiz-component/) to see if there is any diff. Thanks a lot.

**Comment by akmil** [comment]
Added fix for fist issue.
I've tested with :
shuffle={false}
showInstantFeedback={false}
continueTillCorrect={false}
so 2,3rd bug is ok now(turn it back to true).

**Comment by wingkwong** [comment]
Explanation is not rendered (Left: Your PR v.s. Right: Existing Demo)

@akmil Still not able to render.

**Comment by akmil** [comment]
@wingkwong please review

**Comment by wingkwong** [comment]
Thanks a lot. Been occupied these days. I'll review it during the weekend.

**Pull request merged**
