### PR TITLE
Updated quiz filter design

### PR DESCRIPTION
**Pull request by VishakhaSainani**
Fixes : #141 

**SCREENSHOTS :** 

Before : 
IMG-20231022-WA0004

After : 
React Quiz Component Demo - Google Chrome 22-10-2023 22_19_14

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
1. please pull the latest code
2. please run lint 
3. the design isn't good tbh. something like this is preferred.
image

**Comment by wingkwong** [comment]
@VishakhaSainani prefer div but I could take a look ul & li approach first.

**Comment by VishakhaSainani** [comment]
@wingkwong Made a new pull request since had to pull the latest code.

**Comment by wingkwong** [comment]
Closing this PR. will be tracked in above new PR instead.

**Pull request closed without merging**
