### PR TITLE
Added Timer

### PR DESCRIPTION
**Pull request by vr-varad**
Please check it out :}

### CODE REVIEW

**Comment by vr-varad** [comment]
@wingkwong I tried my best but correct me if something is wrong or can be improved

**Review by wingkwong — CHANGES_REQUESTED** [review]
try finish a quiz

image

**Review by wingkwong — COMMENTED** [review]
You can put Timer inside Core and use `endQuiz` to stop. In this way, you don't need to do extra stuff like questionSolved, noOfQuestionAttempted, and etc.

**Comment by vr-varad** [comment]
i first tried using it inside core but as it click next the timer starts again

**Comment by vr-varad** [comment]
@wingkwong is the issue resolved?
or should i make some changes

**Pull request closed without merging**
