### PR TITLE
updated the quiz question

### PR DESCRIPTION
**Pull request by pranav514**
fixes: #148 
I have updated the lorem ipsum question with new options and replace the image
image
@wingkwong pls review it

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
See https://github.com/wingkwong/react-quiz-component/issues/148#issuecomment-1779658744

**Comment by pranav514** [comment]
@wingkwong I have added the new question with image as an option..pls review it

**Review by wingkwong — CHANGES_REQUESTED** [review]
you should use image to display something that you can't display in text.

**Comment by pranav514** [comment]
@wingkwong  I have updated the question and option with the reliable images ,this images belongs to the answer

**Review by wingkwong — CHANGES_REQUESTED** [review]
I'm fine with the question and answers. 

Please copy the images and upload to github editor to get the links. Supposedly I just need 4 simple links with the same source.

**Comment by pranav514** [comment]
@wingkwong  I have updated the image link from the same source ,I think it is good now...

**Review by wingkwong — APPROVED** [review]

**Pull request merged**
