### PR TITLE
v0.3.9

### PR DESCRIPTION
**Pull request by wingkwong**

### CODE REVIEW

**Comment by Weistrand** [comment]
Hey @wingkwong! Looks like my [contribution](https://github.com/wingkwong/react-quiz-component/commit/d8016bfc6c11f5604990eadbd77a60abf22dd1f9) got overwritten during merge. Now the questions are picked out before shuffled, but I want the questions to be shuffled before picking them.

**Comment by wingkwong** [comment]
@Weistrand But it looks like your contribution goes after this merge.

**Comment by Weistrand** [comment]
@wingkwong  Sorry yes, my mistake. Was so sure my last contribution was added to master, but it was only added to the feature branch https://github.com/wingkwong/react-quiz-component/pull/74.

**Comment by wingkwong** [comment]
Ya. will make a release soon. Thanks.

**Pull request merged**
