### PR TITLE
Displaying the results of other quiz participants

### PR DESCRIPTION
**Pull request by jpublic**
If specified in quiz object, we can display the answers from other participants.

(@wingkwong After review/merge, would it be possible to re-publish in npmjs as well? Thanks & best regards: JP)

### CODE REVIEW

**Comment by wingkwong** [comment]
@jpublic thanks for contributing. I'll take a look tonight.

**Comment by wingkwong** [comment]
@jpublic what's the point of this feature? It seems you can only show a very few names here. Besides, you need to update the json file frequently to fill the names.

**Comment by jpublic** [comment]
The main aim is to possibly display the answers given my previous contenders / participants (which can be retreived from a persistent storage and inserted into the quiz object). Could be useful for education purposes, or matching yourself against different AI algorithms :-) for example.

**Comment by jpublic** [comment]
@wingkwong for us it would be good to know if you intend to approve it (with the exception of "width" change in the .css I tried to leave everything backward compatible) or we should move on with an independent fork. (we need to proceed with our delivery soon.)

**Comment by wingkwong** [comment]
@jpublic I'm afraid I couldn't take this PR. I suggest you to use [Custom Result Page](https://github.com/wingkwong/react-quiz-component#enabling-custom-result-page) to render what you want to show.

**Comment by jpublic** [comment]
@wingkwong Unfortunately using the Custom Result Page doesn't suit for situations, when you want to render results after each question. But we'll continue with the fork then.

**Pull request closed without merging**
